# Generated by Django 3.1.4 on 2020-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_expert_data_student_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_data',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
