# Generated by Django 3.1.4 on 2020-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201231_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='imagename',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='imageurl',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
