# Generated by Django 3.1.4 on 2020-12-31 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201231_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_correct_response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcq_correct_question', to='main.mcq_question'),
        ),
    ]
