# Generated by Django 3.1.4 on 2020-12-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201231_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_option',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.competition'),
        ),
    ]
