# Generated by Django 3.1.2 on 2021-01-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_attempted_contests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_type', models.CharField(max_length=200)),
                ('description', models.TextField(default='-')),
                ('imageurl', models.TextField(blank=True, default='-', null=True)),
                ('imagename', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
    ]
