# Generated by Django 3.1.4 on 2021-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_option',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
