# Generated by Django 3.1.4 on 2021-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mcq_option_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ_correct_response',
        ),
    ]
