# Generated by Django 3.1.4 on 2021-01-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_mcq_correct_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='fib_question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcq_student_response',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf_student_response',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
