# Generated by Django 3.1.4 on 2021-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210104_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fib_student_response',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf_question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
